elsagest/elsagest/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
import elsahome.views as home_views
import elsausers.views as users_views
import librosoci.views as librosoci_views
import elsamail.views as email_views
from graphene_django.views import GraphQLView
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.urls import include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/', permanent=False)),
    path('home/', home_views.view, name='home'),
    path('librosoci/', librosoci_views.view, name='libro_soci'),
    path('librosoci/aggiungisocio/', librosoci_views.aggiungi_socio, name="aggiungi_socio"),
    path('librosoci/modificasocio/', librosoci_views.modifica_socio, name="modifica_socio"),
    path('librosoci/modificaconsiglio/', librosoci_views.modifica_consiglio, name="modifica_consiglio"),
    path('graphql/', GraphQLView.as_view(graphiql=True)),
    path('login/', auth_views.login, {'template_name': 'elsausers/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('password/', users_views.change_password, name='change_password'),
    path('impostazioni/', users_views.settings_view, name='impostazioni'),
    path('impostazioni/utente/', users_views.impostazioni_utente, name='impostazioni_utente'),
    path('impostazioni/sezione/nuovo-utente', users_views.nuovo_utente, name='impostazioni_aggiungi_utente'),
    path('librosoci/popola', librosoci_views.popola_db, name='popola_db'),
    path('elsamail/invia_promemoria', email_views.promemoria_scadenza, name='promemoria_scadenza'),
    path('elsamail/componi', email_views.componi_email, name='componi_email'),
    path('elsamail/invia', email_views.invia_email, name='send_email'),
    path('elsamail/unsubscribe/', email_views.unsubscribe, name='unsubscribe'),
    path('elsamail/salva-bozza/', email_views.salva_bozza, name='salva_bozza'),
    path('elsamail/elimina-bozza/', email_views.elimina_bozza, name='elimina_bozza')
]


# url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
# url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
# url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
# url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

elsagest/elsausers/models.py
from django.db import models
from django.contrib.auth.models import User
from librosoci.models import SezioneElsa
from django.db.models.signals import post_save
from django.dispatch import receiver
from simple_history.models import HistoricalRecords
from fernet_fields import EncryptedTextField

# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sezione = models.ForeignKey(SezioneElsa, on_delete=models.CASCADE, default=1)
    history = HistoricalRecords()

    def __str__(self):
        return f"Profilo di {self.user.username}"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()


class EmailCredentials(models.Model):

    username = models.EmailField()
    password = EncryptedTextField()  # will be encrypted... but... BIG security issue!
    host = models.TextField()
    port = models.IntegerField()
    tls = models.BooleanField()
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)

elsagest/elsausers/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Richiesto. Fornisci un indirizzo email valido.')
    email_conf = forms.EmailField(max_length=254, help_text='Richiesto. Conferma l\'indirizzo email.')
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    class Meta:
        model = User
        fields = ('username', 'email', 'email_conf', 'password1', 'password2', )

    def clean(self):
        cleaned_data = super(SignUpForm, self).clean()
        email = cleaned_data.get('email')
        email_conf = cleaned_data.get('email_conf')

        if email and email_conf and email != email_conf:
            self._errors['email_conf'] = self.error_class(['Le email inserite non coincidono'])
            del self.cleaned_data['email_conf']

        return cleaned_data

elsagest/elsausers/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import Group
from django.core.mail import send_mail, get_connection
from django.http import JsonResponse
from django.contrib.auth.forms import PasswordResetForm
from django.http import HttpRequest
from django.conf import settings

from .forms import SignUpForm
from .tokens import account_activation_token
from .models import EmailCredentials
from librosoci.models import Ruolo


def home(request):
    return redirect('/')


def signup(request):

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            subject = 'Attiva il tuo account su ELSA GEST'
            message = render_to_string('elsausers/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            # in realtà non manda un emerito cazzo! TODO
            user.email_user(subject, message)

            return redirect('account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'elsausers/useradd.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'elsausers/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        group = Group.objects.get(name='premium')
        group.user_set.add(user)
        login(request, user)
        return redirect("/")
    else:
        return render(request, 'elsausers/account_activation_invalid.html')


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Password modificata con successo!')
            return redirect('/')
        else:
            messages.error(request, 'Per favore correggi gli errori')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'elsausers/change_password.html', {
        'form': form
    })


def impostazioni_utente(request):
    user = request.user
    if request.method == 'POST':
        try:
            post = request.POST

            username = post.get("email")
            port = post.get("port")
            host = post.get("host")
            password = post.get("password")
            tls = post.get("tls") == "on"

            try:
                credentials = user.userprofile.emailcredentials
                credentials.username = username
                credentials.port = port
                credentials.host = host
                credentials.tls = tls
                if password:
                    credentials.password = password
                try:
                    get_connection(host=host, port=port, username=username, password=password, use_tls=True)
                    credentials.save()
                    return JsonResponse({"success": True, "message": "Impostazioni aggiornate!"})
                except Exception as e:
                    return JsonResponse({"success": False, "message": f"Impossibile accedere: {e}"})
            except:
                if password:
                    credentials = EmailCredentials.objects.create(
                        user=user.userprofile,
                        username=username,
                        port=port,
                        tls=tls,
                        host=host,
                        password=password)
                    get_connection(host=host, port=port, username=username, password=password, use_tls=True)
                    credentials.save()
                    return JsonResponse({"success": True, "message": "Impostazioni aggiornate!"})
                else:
                    return JsonResponse({"success": False, "message": "Specificare una password"})

        except Exception as e:
            return JsonResponse({"success": False, "message": str(e)})


def nuovo_utente(request):
    user = request.user
    sezione = user.userprofile.sezione
    if request.method == "POST":
        try:
            post = request.POST

            username, email1, email2 = post.get('username'), post.get('email1'), post.get('email2')

            if User.objects.filter(username=username):
                JsonResponse({"success": False, "message": f"L'utente esiste già"})

            if email1 != email2:
                return JsonResponse({"success": False, "message": "Le email inserite non coincidono"})

            password = User.objects.make_random_password()
            new_user = User.objects.create(username=username, email=email1, is_active=True, password=password)
            new_user.save()
            new_user.userprofile.sezione = sezione
            new_user.save()
            current_site = get_current_site(request)
            protocol = request.scheme
            send_mail(
                subject="Attiva il tuo account su ELSAGest",
                message=render_to_string('elsausers/welcome_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'protocol': protocol
                }),
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[new_user.email],
                fail_silently=False
            )
            return JsonResponse({"success": True, "message": "È stata inviata una email all'indirizzo indicato"})
        except Exception as e:
            return JsonResponse({"success": False, "message": f"Si è verificato un errore {e}"})


def settings_view(request):
    sezione = request.user.userprofile.sezione
    abbreviazioni_ruoli = set([r.abbreviazione for r in Ruolo.objects.all().order_by('id')
                               if not User.objects.filter(username=f"{r.abbreviazione}.{sezione.domain}")])
    print(abbreviazioni_ruoli)
    context = {
        "user": request.user,
        "sezione": sezione,
        "ruoli": abbreviazioni_ruoli
    }
    return render(request, 'elsausers/settings.html', context=context)

elsagest/elsausers/templates/elsausers/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

elsagest/elsausers/templates/elsausers/account_activation_invalid.html
{% extends 'base/base.html' %}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

elsagest/elsausers/templates/elsausers/account_activation_sent.html
{% extends 'base/base.html' %}

{% block content %}
<div role="alert" class="alert alert-info text-center">
    <span>Ti abbiamo inviato una email per confermare la tua iscrizione</span>
</div>
{% endblock %}

elsagest/elsausers/templates/elsausers/change_password.html
{% extends 'base.html' %}

{% load render_bundle from webpack_loader %}

{% block content %}

{%  load static %}
<link rel="stylesheet" href="{% static 'assets/css/Login-Form-Clean.css' %}">
<div class="login-clean">
    <div class="col-md-3 col-md-offset-4">

        <form method="post"> {% csrf_token %}
            <input type="hidden" name="next" value="/home"/>
            <h2 class="text-center">Modifica la tua password</h2>
            {% if form.errors %}
            <p style="color: red; text-align:center">Password errata.<br/>Prova di nuovo.</p>
            {% endif %}
            <div class="form-group">
                <input class="form-control" type="password" name="old_password" autofocus required id="id_old_password"
                       placeholder="Password attuale">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="new_password1" required id="id_new_password1"
                       placeholder="Nuova password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="new_password2" required id="id_new_password2"
                       placeholder="Conferma nuova password">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">Conferma</button>
            </div>
            <a href="#" class="forgot">Password dimenticata?</a><br/>
        </form>
    </div>
</div>

{% endblock %}

elsagest/elsausers/templates/elsausers/login.html
{% extends "base.html" %}

{% load render_bundle from webpack_loader %}

{% block content %}

<!-- temporaneo, in attesa di un custom template -->

<div class="login-clean">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
        <form method="post"> {% csrf_token %}
            <input type="hidden" name="next" value="/"/>
            <h2 class="text-center">Accedi</h2>
            {% if form.errors %}
            <p style="color: red; text-align:center">Username o password errati.<br/>Prova di nuovo.</p>
            {% endif %}
            <div class="form-group">
                <input class="form-control" type="text" name="username" placeholder="Username"/>
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password"/>
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">Accedi</button>
            </div>
            <a href="{% url 'password_reset' %}" class="forgot">Password dimenticata?</a><br/>
        </form>
        </div>
    </div>
</div>

{% endblock %}

elsagest/elsausers/templates/elsausers/settings.html
{% extends "base.html" %}

{% load render_bundle from webpack_loader %}

{% block extra_css %}
{% render_bundle 'common' 'css' %}
{% endblock %}

{% block content %}

<!-- temporaneo, in attesa di un custom template -->

<div class="container">
    <div class="row">
        <div class="col-md-10 ">
            <form class="form-horizontal settings" id="form-impostazioni-utente" action="{% url 'impostazioni_utente' %}">
                <fieldset>

                    <!-- Form Name -->
                    <legend>Impostazioni Utente</legend>

                    <!-- Text input-->
                    {% autoescape off %}

                    <!-- USERNAME -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="username">Username</label>
                        <div class="col-md-4">

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-user"></i>

                                </div>
                                <input id="username" name="username" type="text" placeholder="Username"
                                       class="form-control input-md" value="{{ user.username }}" disabled>
                            </div>
                            <a href="/password/">Cambia password</a>
                        </div>
                    </div>

                    <!-- EMAIL -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="email">Email</label>
                        <div class="col-md-4">

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-envelope"></i>

                                </div>
                                {% if user.userprofile.emailcredentials.username %}
                                <input id="email" name="email" type="text" placeholder="Email"
                                       class="form-control input-md"
                                       value="{{ user.userprofile.emailcredentials.username }}" required>
                                {% else %}
                                <input id="email" name="email" type="text" placeholder="Email"
                                       class="form-control input-md" value="{{ user.email }}" required>
                                {% endif %}
                            </div>

                        </div>
                    </div>


                    <!-- HOST SMTP -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="server-smtp">Server SMTP</label>
                        <div class="col-md-4">

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-server"></i>

                                </div>
                                <input id="server-smtp" name="host" type="text" placeholder="smtp.iltuohost.com"
                                       class="form-control input-md"
                                       value="{{ user.userprofile.emailcredentials.host }}" required>
                            </div>


                        </div>
                    </div>

                    <!-- PORTA SMTP -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="porta-smtp">Porta SMTP</label>
                        <div class="col-md-4">

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-cog"></i>

                                </div>
                                <input id="porta-smtp" name="port" type="text" placeholder="es. 587"
                                       class="form-control input-md"
                                       value="{{ user.userprofile.emailcredentials.port }}" required>
                                <span class="input-group-addon"><input type="checkbox" checked name="tls"/> TLS</span>
                            </div>

                        </div>
                    </div>

                    <!-- PASSWORD -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="password-email">Password email</label>
                        <div class="col-md-4">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-lock"></i>

                                </div>
                                <input id="password-email" name="password" type="password"
                                       placeholder="La password dell'email"
                                       class="form-control input-md">

                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3"></div>
                        <div class="col-md-3 form-result"></div>
                        <div class="col-md-3">
                            <button class="btn btn-default btn-primary float-right" type="submit">Salva</button>
                        </div>
                    </div>
                    {% endautoescape %}
                </fieldset>
            </form>

            <!-- FORM IMPOSTAZIONI SEZIONE -->

            <fieldset>

                <!-- Form Name -->
                <legend>Impostazioni ELSA {{sezione.nome}}</legend>
                <form class="form-horizontal settings" id="form-aggiungi-utente" action="{% url 'impostazioni_aggiungi_utente' %}">

                    <!-- Text input-->
                    {% autoescape off %}

                    <h4 class="text-center">Aggiungi un nuovo amministratore</h4>

                    <!-- USERNAME -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="username">Username</label>
                        <div class="col-md-4">

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-user"></i>

                                </div>
                                <select name="username" class="form-control">
                                    {% for ruolo in ruoli %}
                                    <option value="{{ruolo}}.{{sezione.domain}}">{{ruolo}}.{{sezione.domain}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>

                    <!-- EMAIL -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="email">Email</label>
                        <div class="col-md-4">

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-envelope"></i>

                                </div>
                                <input id="new_email1" name="email1" type="text" placeholder="Email"
                                       class="form-control" required>
                            </div>

                        </div>
                    </div>


                    <!-- CONFERMA EMAIL -->
                    <div class="form-group">
                        <label class="col-md-4 control-label" for="email">Conferma email</label>
                        <div class="col-md-4">

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-envelope"></i>

                                </div>
                                <input id="new_email2" name="email2" type="text" placeholder="Conferma Email"
                                       class="form-control" required>
                            </div>

                        </div>
                    </div>

                    {% endautoescape %}
                    <div class="form-group">
                        <div class="col-md-3"></div>
                        <div class="col-md-3 form-result"></div>
                        <div class="col-md-3">
                            <button class="btn btn-default btn-primary float-right" type="submit">Salva</button>
                        </div>
                    </div>
                </form>
            </fieldset>

        </div>
        <div class="col-md-2 hidden-xs">
            <img src="http://websamplenow.com/30/userprofile/images/avatar.jpg"
                 class="img-responsive img-thumbnail ">
        </div>


    </div>
</div>

{% endblock %}

{% block extra_js %}
{% render_bundle 'common' 'js' %}
{% render_bundle 'elsausers' 'js' %}
{% endblock %}

elsagest/elsausers/templates/elsausers/useradd.html
{% extends "base/base.html" %}
{% block content %}

<!-- temporaneo, in attesa di un custom template -->
{% load render_bundle from webpack_loader %}

{% block extra_css %}
    {% render_bundle 'users_core' 'css' %}
{% endblock %}

<div class="login-clean">
    <form method="post"> {% csrf_token %}
        <h2 class="text-center">Registrati</h2>
        {% for field in form %}
        {% for error in field.errors %}
        <p style="color: red; text-align: center">{{ error }}</p>
        {% endfor %}
        {% endfor %}

        <div class="form-group">
            <input class="form-control" type="text" name="username" maxlength="150" autofocus required id="id_username"
                   placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" maxlength="254" required id="id_email"
                   placeholder="Email">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email_conf" maxlength="254" required id="id_email_conf"
                   placeholder="Conferma email">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password1" required id="id_password1"
                   placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password2" required id="id_password2"
                   placeholder="Conferma password">
        </div>
        <div class="form-group">
            <button class="btn btn-primary btn-block" type="submit">Registrati</button>
        </div>
        <a href="/login/" class="forgot">Sei già registrato? Accedi adesso</a>
    </form>
</div>
{% endblock %}


{% block extra_js %}
    {% render_bundle 'users_core' 'js' %}
{% endblock %}

elsagest/elsausers/templates/elsausers/welcome_email.html
{% autoescape off %}
Per attivare il tuo account clicca qui sotto e resetta la tua email:

{{ protocol }}://{{ domain }}{% url 'password_reset' %}

{% endautoescape %}